[package]
name = "csshw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "csshw"
path = "src/main.rs"

[[bin]]
name = "csshw-daemon"
path = "src/daemon/main.rs"

[[bin]]
name = "csshw-client"
path = "src/client/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
rmp = "0.8.11"
ssh2-config = "0.1.6"
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread", "net", "sync", "macros", "time", "signal"] }
[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_Graphics_Gdi",
]
